name: Lint

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  MDBOOK_VERSION: v0.4.40

jobs:
  license:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL "https://github.com/rust-lang/mdBook/releases/download/$MDBOOK_VERSION/mdbook-$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --directory=bin

      - name: Build
        run: |
          bin/mdbook build
