name: Build

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out and build
        uses: ./actions/build
