name: Build

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  MDBOOK_VERSION: v0.4.40
  LINKCHECK_VERSION: v0.7.7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install mdbook
        run: |
          mkdir -p bin
          curl -sSL "https://github.com/rust-lang/mdBook/releases/download/$MDBOOK_VERSION/mdbook-$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --directory=bin

      - name: Install mdbook-linkcheck
        run: |
          mkdir -p bin
          curl -sSL "https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/$LINKCHECK_VERSION/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip" | ditto -x -k - bin

      - name: Build
        run: |
          PATH=$PWD/bin:$PATH mdbook build
