name: Lint

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint license
        run: |
          cargo xtask lint-license

      - name: Lint filenames
        run: |
          cargo xtask lint-filenames
